# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
      args:
        - --line-length=100
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
        - --max-line-length=100
        - --ignore=E203, E266, E501, W503, F403, F401
        - --max-complexity=18
        - --select=B,C,E,F,W,T4,B9

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args:
        - --line-length = 100
