version: "3.6"

services:
  send2hec:
    image: send2hec
    build:
      context: send2hec
      args:
        GIT_HASH: ${GIT_HASH}
  pub:
    image: pub
    build:
      context: pub
      args:
        GIT_HASH: ${GIT_HASH}